version: "3.3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"

    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

    depends_on:
      - mongo

  cache:
    image: memcached
    ports:
      - "11211:11211"

  dbfaker:
    build: DbFaker
    environment:
      DBSERVER: mongo
      DBCOUNT: 1000000
      
    depends_on:
      - mongo

  myservice:
    build: MyService
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - DOTNET_URLS=http://+:5000
      
    ports:
      - "5000:5000"
      
    depends_on:
      - dbfaker
     
    
